### ISSUE TITLE
Variation of Reynolds number

### ISSUE THREAD

**Issue by AndreWeiner** [Tushargh29/transonic_shock_buffet#14]
Hi Tushar,
great job starting the new setup on the cluster. Unfortunately, there is still no buffeting. To make the computation easier, I suggest going to lower Reynolds numbers. After merging the latest pull request, I would like you to try the following:
- create a refined version of the base case; to do so, double the number of cells per block in the blockMeshDict, something like
```
    // Number of cells
    yCells  320; // airfoil to far field
    yGap     16;  // resolution of trailing edge
    xUCells 120;  // upstream
    xMCellsLower 200; // middle low
    xMCellsUpper 200; // middle up
    xDCells 420; // downstream
```
- for default and fine mesh, vary the Reynolds number while keeping the Mach number and the angle of attack fixed at 0.85 and 5°; for the Reynolds number, I suggest values of Re={0.375, 0.75, 1.5, 3} Mio (8 simulations in total)
- for the fine mesh, use 8 MPI tasks; see [here](https://github.com/Tushargh29/transonic_shock_buffet/pull/12) how to do this
- set the final simulation times to {2.4, 1.2, 0.6, 0.3}s and the writeInterval to {0.008, 0.004, 0.002, 0.001}  (controlDict)
- to scale the mesh, e.g., to adjust the Reynolds number, change the *scale* parameter in blockMeshDict, e.g. `scale 0.157637;`
- if you change the scale parameter or the inlet velocity, you also have to update the parameters magUInf, lRef, and Aref in *FOforces*; lRef is the chord length (the same value as you use for scaling); Aref is the projected area in lift-direction (the chord length times the depth of our profile (depth is always 0.02)); magUInf is the magnitude of the inlet velocity vector
- the angle of attack in this setup is implemented by changing the direction of the inlet velocity vector rather than rotating the geometry; the script *compute_inlet_vector.py* helps you to determine the velocity vector for new speeds
- set the time parameter in jobscript to 48:00:00

How to create a new setup:
- make a copy of the base case in test_cases; give the folder a sensible name, e.g., naca-Re-0.375-Ma-0.85-fine
- adjust the settings in the new case
- make a copy of the jobscript and adjust the folder names
- submit the new jobscript

Let's see if we can find a suitable setup. Let me know if the instructions are not clear enough.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,
I mailed you quite a few minutes ago, but I solved that doubt so no need of having a Skype discussion.
Sorry for your inconvenience.

I just have a small doubt in above instructions rest everything I understood properly.
You said If we need to implement 8MPI tasks, I need to change the _numberOfSubdomains = 8_ instead of _numberOfSubdomains = 2_ in the _decomposeParDict_ that I understood .

But I could change at only one place in the jobscript which is _#SBATCH --ntasks-per-node=8_ . Could you please tell me what should I change in the jobscript apart from this? As you have mentioned **"the number of processes has to be changed in the jobscript (twice)  and in the decomposeParDict."**. I think you meant make changes twice in two separate files instead of twice in the single jobscript.
Nevertheless, correct me If I am wrong.

Thank you.

Regards,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
in the jobscript, there are two numbers you have to change:

- `#SBATCH --ntasks-per-node=8 ` as you mentioned already
- `./Allrun 8`

The number of tasks is also passed as argument to the *Allrun* script.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks a lot. I understood.
Last question: Suppose I create all the 8 sets of simulation for both base and refined cases, can start simulation of all the 8 cases simultaneously on the cluster? Is that possible? If yes then it would save a lot of time. 

Having said that I can do not 8 but at least 4 cases of refined setup in parallel at a time  and then 4 cases of default setup later.

Please suggest.
Thank you.

**Comment by AndreWeiner** [comment]
Yes, that is possible. You create one jobscript for each case and then submit the individual jobscripts using sbatch.

**Comment by Tushargh29** [comment]
Perfect. I got the idea. I will get back to you soon.

Thanks Sir.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

I have created 8 separate jobscripts and submitted on cluster for simulation.
At this moment all 8 simulations have started running.
I will get back to you soon once the simulations are done with the Paraview results.
Thank you.

Regards,
Tushar
![Screenshot from 2021-01-11 22-41-26](https://user-images.githubusercontent.com/71929988/104241954-b5e0ce00-545e-11eb-9b3d-9f02cad05402.png)

**Comment by Tushargh29** [comment]
Hello Sir, 
As per our today's discussion, I have plotted the graphs for all 8 cases. 
But as expected the refined cases of low Reynolds cases have not generated so many outputs so the graphs are not so beneficial and explanatory.
Please have a look on it.

Suggest me further instructions.
Thank you.

Regards,
Tushar
![results_plots](https://user-images.githubusercontent.com/71929988/104473953-d07d8900-55bd-11eb-9b51-6f373f3afd75.png)

**Comment by AndreWeiner** [comment]
Hi Tushar,

Thanks for the update. I suggest the following:
- refine both meshes since it is already visible that the base mesh is too coarse in all cases
```
    // Number of cells for new base mesh
    yCells  320; // airfoil to far field
    yGap     16;  // resolution of trailing edge
    xUCells 120;  // upstream
    xMCellsLower 200; // middle low
    xMCellsUpper 200; // middle up
    xDCells 420; // downstream

    // Number of cells for new fine mesh
    yCells  640; // airfoil to far field
    yGap     32;  // resolution of trailing edge
    xUCells 240;  // upstream
    xMCellsLower 400; // middle low
    xMCellsUpper 400; // middle up
    xDCells 840; // downstream
```
- run the new base cases with 8 and the new fine cases with 16 cores
- set the final simulation time to {0.0375, 0.075, 0.15, 0.3} and the write time interval to {1.25E-4, 2.5E-4, 5.0E-4, 1.0E-3}
- set the requested time in the jobscript to 120 hours

Before you synchronize the new simulations (in one of the next days), make sure to delete the old simulations locally and on the cluster.

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

I got the instructions.
Thank you.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,
As per your instructions, I made necessary changes in all 8 cases, I have submitted the jobscripts on the cluster.
I will let you know what further things soon.
Thank you.

Regards,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Just to give you an update, I want to say that the simulation of cases are still running for almost 110 hours out of 120.

I checked the output folders in every case on cluster. I noticed that base cases have generated many outputs than the refined cases. It is seems that some cases would not finish within 120 hours.

Thank you.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
It's OK if they haven't finished yet. It's important to check the force coefficients over time. Do you observe unsteady oscillatory behavior?
Best, Andre

**Comment by Tushargh29** [comment]
Okay Sir.

I forgot to mention that I checked the Cl vs time in gnuplot.
But It was something like this:
![Screenshot from 2021-01-18 14-29-48](https://user-images.githubusercontent.com/71929988/104924503-d13b6400-599d-11eb-9fbd-df4761c0cbd4.png)

Because of this the plot is not getting generated. Could you please tell me what is this _unknown type_.
Thank you.

Best regards,
Tushar

**Comment by AndreWeiner** [comment]
You need to start Gnuplot locally and not on the cluster. Copy the data to your workstation and open it there with Gnuplot.
Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Please have a look on it.
Thank you.

Best regards,
Tushar
![results_plots2](https://user-images.githubusercontent.com/71929988/105095211-b3592680-5aa5-11eb-80b4-8422aeea49e6.png)

**Comment by Tushargh29** [comment]
Hello Sir,

I just want your confirmation on the changes I made for the refined cases before restarting the simulation on cluster.
Please have a look on the two images which reflect the revised changes.
Correct me if I need to change something.

Thanks.

Best,
Tushar
![Allrun](https://user-images.githubusercontent.com/71929988/105177039-5e112980-5b26-11eb-94a1-6d92c6a2a3cd.png)
![jobscript](https://user-images.githubusercontent.com/71929988/105177044-610c1a00-5b26-11eb-82ef-bb31b31cc0f7.png)

**Comment by AndreWeiner** [comment]
Looks good!

**Comment by Tushargh29** [comment]
Hello Sir,

I have a small doubt:
Suppose I want to implement SA model instead of kOmegaSST model in some cases.
Then I need to change the _RASModel            kOmegaSST;_ in _turbulenceProperties_ file. Do I need to change something more. Please let me know.

Thank you.

Best,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,

if you navigate to
```
cd $FOAM_TUTORIALS/incompressible/simpleFoam/airFoil2D
```
you find a simulation setup using the Spalart-Allmaras (SA) turbulence model. The SA model solves one additional transport equation for a field called *nuTilda* in OpenFOAM. Files you have to change are
- constant/turbulenceProperties
- 0/nuTilda (not present in your setup)
- system/fvSolution (linear solver setting for nuTilda)
- system/fvSchemes (discretization of the nuTilda transport equation)

Best, Andre

**Comment by Tushargh29** [comment]
Hello Sir,

Thanks a lot for your suggestions.

There are some things to discuss:
1. I have prepared cases to be performed on the cluster, I am planning to run atleast 30 cases(max 40) at a time on the cluster. Is that fine? Please let me know.

2. Currently, we are are having alpha of 5 degrees right? Please confirm. If I want to change the alpha values; I am not getting the proper location to see the value of alpha so that I can change it there, also I believe that it is not necessary to change other things when alpha is changed just like we did for change in Re number(adjusting scaling factor and all).

3. Also, the Baldwin-Lomax Algebraic Stress model is also successful in some NACA0012 airfoil setups with higher Reynolds number(6Mio and 10 Mio). Shall I give a try on this? If yes, I cannot find the proper approach to implement BL Algebraic Stress model in OpenFoam.

4. Lastly, I am planning to put the final hours of 250 hours for cluster in the jobscripts.

Please let me know what you think about these points.

Best,
Tushar

**Comment by AndreWeiner** [comment]
Hi Tushar,
1) Please do not start more than 10 cases in addition to the refined cases. You can always stop simulations that do not show promising results and start other simulations instead
2) The angle of attack is currently 5° in all simulations; to change it, you have to change the direction of the inlet velocity vector in *0.orig/U*
3) There are no algebraic stress models in OpenFOAM; a list of turbulence models is available [here](https://www.openfoam.com/documentation/guides/latest/doc/guide-turbulence.html).
4) Please keep the time in the jobscripts as is; we rather want to restart promising results after an intermediate time.

Best, Andre

**Comment by Tushargh29** [comment]
Thank you sir.
I will start the work and let you know soon.

Best,
Tushar

**Comment by Tushargh29** [comment]
Hello Sir,

Some doubts:
1. Whenever I am changing Mach no, inlet velocity is getting changed, so accordingly I am changing the scaling factor in _blockMeshDict_ and _FOforces_ files. But I noticed that the inlet velocity vector in _0.orig/U_ and python script also take the value of inlet velocity. So do I need to change these values in these two locations everytime when Mach no changes?

2. How the direction of inlet velocity vector changes if I change the alpha? I am confused.

3. The foam tutorials of OpenFoam uses _simpleFoam_ for SA models, do I need to implement _simpleFoam_ or just make necessary changes keeping _rhoPimpleFoam_? in case of implementation of SA models.

4. The restarted refined cases are still running, its been almost seven days from the start? Is it really taking this much time or am I going wrong somewhere?

Please let me know. So that I can work on this in the weekend.

Thank you.

Regards,
Tushar.

**Comment by AndreWeiner** [comment]
Tushar,

1. You change the Mach number by adjusting the speed at the inlet; additionally, the angle of attack defines the direction of the inlet velocity vector; if you change Ma or alpha, you need to recompute the inlet velocity vector; the Python script helps you to do that; if you change Ma but want to keep the Reynolds number constant, you have to rescale the chord length (blockMeshDict)
2. the angle of attack is the angle between the inlet velocity vector and the x-axis (along which the airfoil is oriented); to change the angle of attack, we change the direction of the inlet velocity vector rather than the orientation of the airfoil; the Python script helps you to compute the correct inlet velocity vector for given angle of attack and speed
3. the fine cases won't finish within the specified time on the cluster; however, you should regularly check that the results look plausible
